global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'inference-service'
    static_configs:
      - targets: ['inference-service:8001']

  - job_name: 'tensorflow-serving'
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['tensorflow-serving:8501']